Merge branch 'release'
product-definition-center/pdc-contact-browser pull request #63
Opened 2017-12-11 12:05 UTC by hluk

2017-12-12 10:17 UTC, lubomir requested changes
Do we really want to commit the generated `assets/` directory?

2017-12-12 10:17 UTC, lubomir commented on pdc-contact-browser.spec
> +- add assets for packaging
Ideally there should be an empty line here to be consistent with rest of the changelog

2017-12-12 10:48 UTC, hluk commented
> Do we really want to commit the generated assets/ directory?

Oh, if it's generated directory, then no, ideally it shouldn't be in the repo.

Since this is simple merge commit, I'll create another PR for release branch.

2017-12-12 11:19 UTC, lubomir commented
I believe it is created by `npm run build:webpack`

2017-12-14 08:11 UTC, hluk commented
@lubomir This merge now contains the fixes from PR #66.

2017-12-14 08:20 UTC, lubomir approved these changes

2017-12-14 08:25 UTC, merged